name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Run JS unit tests
        run: npm run test:js

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: python_backend/requirements-dev.txt

      - name: Set environment variable for macOS compatibility
        if: matrix.os == 'macos-13'
        run: echo "SETUPTOOLS_USE_DISTUTILS=stdlib" >> $GITHUB_ENV

      - name: Install Python dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r python_backend/requirements-dev.txt
          python -m pip install reportlab pymupdf

      - name: Run Python unit tests
        run: python -m pytest -q

      - name: Generate test documents and run enhanced tests
        run: |
          python generate_test_documents.py
          python example_test_with_documents.py
